### ISSUE TITLE
extra 'src' in sys.path

### ISSUE THREAD

**Issue by ztzhang** [vye16/deformable-sprites#1]
In https://github.com/vye16/deformable-sprites/blob/e9bf78ab37d9b08fe4d5f7e06f990178770533c5/scripts/run_raft.py#L23, the extra 'src' raises errors for imports.

**Comment by MqLeet** [comment]
yeah, this is also annoying me

> In
> 
> https://github.com/vye16/deformable-sprites/blob/e9bf78ab37d9b08fe4d5f7e06f990178770533c5/scripts/run_raft.py#L23
> 
> , the extra 'src' raises errors for imports.

**Comment by vye16** [comment]
Thanks! Fixed in commit [52327e4](https://github.com/vye16/deformable-sprites/commit/52327e42ad6969459c82e44b36e7c009654880bf).
