### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by Sharpiless** [vye16/deformable-sprites#3]
```
def save_img_dir(out, vis_batch):
    N, _, H, W = vis_batch.shape
    os.makedirs(out, exist_ok=True)
    for i in range(N):
        path = f"{out}/{j:05d}.png"
        imageio.imwrite(path, vis_batch[i])
```

Quite an obvious code error in utils/misc.py that stops running. Do you plan to recheck and run the code to prevent such errors?

**Comment by vye16** [comment]
Fixed in commit [22c368b](https://github.com/vye16/deformable-sprites/commit/22c368b06b03eef0a0057292d0b10ec5b1a8632c)
